version: '2'

services:
  release-monitor:
    image: budry/release-monitor
    build:
      dockerfile: Dockerfile.development
      context: ./
    command: "make run"
    volumes:
      - ./:/go/src/github.com/budry/release-monitor
      - .data/config.json:/etc/release-monitor/config.json