version: '2'

services:
  release-monitor:
    image: budry/release-monitor
    build: .
    command: "make run"
    volumes:
      - ./:/go/src/bitbucket.org/budry/release-monitor
      - .data/config.json:/etc/release-monitor/config.json